name: swoole-install CI

on: [ push, pull_request ]

jobs:
  ubuntu-native-build:
    if: 0
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: native ubuntu install swoole
        run: |
          sudo sh init.sh
          sudo bash install.sh --install-php 1 --install-phpy --install-python3 1
      - name: show info
        run: |
          php -v
          php -m
          php --ri swoole
          php --ri phpy

  linux-container:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: 1
    strategy:
      matrix:
        container_image:
          - ubuntu:20.04
          - ubuntu:24.10
          - debian:11
          - debian:12
          - kalilinux/kali-rolling
          - alpine:3.18
          - rockylinux:9.3
          - fedora:41
          - archlinux:latest
          - php:8.3-zts-alpine3.20
          - php:8.2-zts-alpine3.20
          - php:8.1-zts-alpine3.20
          - php:8.1-zts-bullseye
          - php:8.2-zts-bullseye
          - php:8.3-zts-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: install-swoole
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.container_image }}
          options: -v ${{ github.workspace }}:/work -w /work -e GITHUB_ACTIONS="true"
          env:
          run: |
            sh init.sh
            bash install.sh --install-php 1 --install-phpy --install-python3 1

  macos:
    runs-on: ${{  matrix.macos_version }}
    timeout-minutes: 15
    if: 0
    strategy:
      matrix:
        macos_version:
          - macos-12
          - macos-13
          - macos-14
    steps:
      - uses: actions/checkout@v4
      - name: install swoole
        run: |
          bash install.sh --install-php 1 --install-phpy --install-python3 1
      - name: show info
        run: |
          php -v
          php --ini
          php -m
          php --ri swoole
          php --ri phpy
